#password generator tool cyber shana
import os
import time
import random
os.system("clear")
time.sleep(0.8)
print("\033[31m °•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°")
time.sleep(0.8)
print("""\033[34m
 
█▀▀█ █▀▀█ █▀▀ █▀▀ █───█ █▀▀█ █▀▀█ █▀▀▄ 
█──█ █▄▄█ ▀▀█ ▀▀█ █▄█▄█ █──█ █▄▄▀ █──█ 
█▀▀▀ ▀──▀ ▀▀▀ ▀▀▀ ─▀─▀─ ▀▀▀▀ ▀─▀▀ ▀▀▀─   """)
time.sleep(0.5)
print()
time.sleep(0.2)
print()
time.sleep(0.8)
print(""" \033[32m										
█▀▀ █▀▀ █▄░█ █▀▀ █▀█ ▄▀█ ▀█▀ █▀█ █▀█
█▄█ ██▄ █░▀█ ██▄ █▀▄ █▀█ ░█░ █▄█ █▀▄    """)
time.sleep(0.3)
print()
print()
print()
time.sleep(0.8)
print(" \033[95m           [•]    ✨️°Tool Ctrate By°✨️                 ")
print()
time.sleep(0.8)
print(" \33[36m              [•]    🎭Cyber SHANA👑                      ")
print()
time.sleep(0.8)
print("\033[31m                    [•]  ⚖️ᴼʷⁿᵉʳ_¢увєя вα¢к ѕнσт 🎭                        ")
print()
time.sleep(0.8)
print("\033[0m*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*")
print()
time.sleep(0.3)
print()
time.sleep(0.8)
print("\033[36m         ☞  What do you create a password for?  ☜  ")
print()
time.sleep(0.5)
print("\033[41m        1.Phone screen lock \n \033[0m ") 
time.sleep(0.5)
print("\033[41m        2.Facebook\n \033[0m ")
time.sleep(0.5)
print("\033[41m        3.instagram\n \033[0m ")
time.sleep(0.5)
print("\033[41m        4.Twitter\n \033[0m ")
time.sleep(0.5)
print("\033[41m        5.G-Maill\n \033[0m ")
time.sleep(0.8)
print("\033[41m        6.Other\n \033[0m ")
time.sleep(0.5)
print()
print()
length = int(input(" \033[32m ❰❰❰✒Enter your choice :- "))
print()
print()
time.sleep(0.8)
print()
time.sleep(0.5)
print("\033[95m°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°•°")
print()
print()
time.sleep(0.8)
x = str(input("\033[93m ❰❰❰✒What is your First name :- "))
time.sleep(0.3)
print()
time.sleep(0.8)
y = str(input("\033[93m ❰❰❰✒What is your second name :-"))
time.sleep(0.3)
print()
time.sleep(0.8)
z = str(input("\033[93m ❰❰❰✒What is your favorite nickname :- "))
time.sleep(0.2)
print()
time.sleep(0.8)
o = str(input("\033[93m ❰❰❰✒What is your favorite number :- "))
time.sleep(0.2)
print()
time.sleep(0.8)
c = str(input("\033[93m ❰❰❰✒Your favorite color :- "))
time.sleep(0.2)
print()
time.sleep(0.8)
f = str(input("\033[93m ❰❰❰✒Your birthday :- "))
time.sleep(0.2)
print()
time.sleep(0.8)
g = str(input("\033[93m ❰❰❰✒The name of your best friend :- "))
time.sleep(0.8)
print()
print()
print(" \033[0m____________________________________")
time.sleep(0.3)
print()
print()
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
print("\33[36m Your password is being generated..............")
print()
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
print("\33[36m Your password is being generated..............")
print()
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print("\33[36m Your password is being generated..............")
print()
time.sleep(0.8)
print()
print()
print(" \033[0m ____________________________________")
time.sleep(0.8)
print()
print()
time.sleep(0.8)
mix=x+y+z+o+c+f+g
print()
time.sleep(0.5)
print(" \033[31m 🔓 🔑 Your password has been created in a secure manner 🛠️ 🎭 ")
print()
print()
print(" \033[0m ____________________________________ ")
time.sleep(0.8)
print()
print()
print("\033[0m#uplord your password")
time.sleep(0.8)
print()
print("#uplord your password")
time.sleep(0.8)
print()
print("#uplord your password")
time.sleep(0.8)
print()
print("#uplord your password")
time.sleep(0.8)
print()
print("#uplord your password")
print()
print("#uplord your password")
print()
print("#uplord your password")
print()
print("#uplord your password")
print()
time.sleep(0.8)
print("#uplord your password")
print()
print("#uplord your password")
print()
print("#uplord your password")
print()
print("#uplord your password")
time.sleep(0.8)
print()
print("#uplord your password")
time.sleep(0.4)
print()
print(" \033[0m____________________________________")
Password="".join(random.sample(mix,length+5))
print()
print()
time.sleep(0.8)
print("\033[36m You pasword :-- " +  Password)
time.sleep(0.8)
print()
print()
print("\033[32m ☝️This password was created for you☝️ ")
time.sleep(0.8)
print()
print()
time.sleep(0.8)
print(" \033[95m ❤ It can be copied and used🎭🤝 ")
